name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish images
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        publish: true
        imageName: hyr326/apioak
        tag: latest
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword : ${{ secrets.DOCKER_PASSWORD }}
